name: Publish package to pub.dev

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

#    container:
#      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setup credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_login.sh
      - name: Install dependencies
        run: flutter pub get
      - name: Document plugin
        run: |
          export FLUTTER_ROOT="$FLUTTER_HOME"
          pub global activate dartdoc
          pub global run dartdoc
      - name: Publish plugin
        run: flutter pub publish --force
